<a href="https://colab.research.google.com/github/zaidensarii/Pytorch-Fundamentals/blob/main/Pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Main Take away for deep Learning

**Start with random data --> Look at data --> Update random numbers --> Look at data --> Update random numbers**

Machine Learning models like neural networks manipulate and seek patterns in tensors.

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import torch

In [ ]:
print(torch.__version__)

2.2.1+cu121


Introduction to Tensors

Creating tensors

Pytorch tensors are created using 'torch.tensor()'

In [ ]:
# scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# Tensors

Tensor = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 6]]])

Tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 6]]])

In [ ]:
Tensor.ndim

3

In [ ]:
Tensor.shape

torch.Size([1, 3, 3])

Random Tensors

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

In [ ]:
# create a Random tensor of size (3, 4)

random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.8245, 0.6684, 0.3763, 0.9362],
        [0.4039, 0.5133, 0.8246, 0.6651],
        [0.1761, 0.1476, 0.2930, 0.5490]])

In [ ]:
random_tensor.ndim

2

In [ ]:
# creating a random tensor with similar shape to an image tensor

random_image_tensor = torch.rand(size=(224, 224, 3)) # height width Color channel
random_image_tensor.ndim, random_image_tensor.shape

(3, torch.Size([224, 224, 3]))

# Zeros and Ones

Creating tensors from zeros and ones

This happens a lot with masking (like masking some of the values in one tensor with zeros to let a model know not to learn on them)

In [ ]:
zero = torch.zeros(size=(3, 224, 224))
zero

tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]])

In [ ]:
one = torch.ones(size=(3, 34, 34))
one

tensor([[[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.]],

        [[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.]],

        [[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.]]])

# Creating a range of tensors and tensors-like


In [ ]:
one_to_ten = torch.arange(start=0, end=10, step=2)
one_to_ten

tensor([0, 2, 4, 6, 8])

In [ ]:
# creating tensors like

ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0])

# Tensor Datatypes


Tensors datatype is one of the three big errors you'll run into pytorch & deep learning.

1. tensors not right datatype
2. tensors not right shape
3. tensors not on the right device



In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16,
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_64_tensor = float_32_tensor.type(torch.double)
float_64_tensor

tensor([3., 6., 9.], dtype=torch.float64)

# Getting information from tensors

In [ ]:
some_tensor = torch.rand(size=(3,4))

print(some_tensor)
print(f"Shape of the tensor: {some_tensor.shape}")
print(f"Datatype of the tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}")

tensor([[0.0710, 0.5354, 0.5937, 0.0493],
        [0.5603, 0.0217, 0.2540, 0.5202],
        [0.6675, 0.0454, 0.4674, 0.5247]])
Shape of the tensor: torch.Size([3, 4])
Datatype of the tensor: torch.float32
Device tensor is stored on: cpu




```
# This is formatted as code
```

# Manipulating Tensors

In [ ]:
tensor1 = torch.tensor([1, 2, 3])
tensor1 + 10

tensor([11, 12, 13])

In [ ]:
tensor1 * 10

tensor([10, 20, 30])

In [ ]:
tensor1 = tensor1 - 10
tensor1

tensor([-9, -8, -7])

In [ ]:
tensor1 = tensor1 + 10
tensor1

tensor([1, 2, 3])

In [ ]:
torch.mul(tensor1, 10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor1, 10)

tensor([11, 12, 13])

In [ ]:
torch.matmul(tensor1, tensor1)

tensor(14)

In [ ]:
tensor1 @ tensor1

tensor(14)

In [ ]:
%%time
# Matrix multiplication by hand
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor1)):
  value += tensor1[i] * tensor1[i]
value

CPU times: user 465 µs, sys: 82 µs, total: 547 µs
Wall time: 4.32 ms


tensor(14)

In [ ]:
%%time
torch.matmul(tensor1, tensor1)

CPU times: user 65 µs, sys: 11 µs, total: 76 µs
Wall time: 82 µs


tensor(14)

In [ ]:
tensor2 = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6]],
                       dtype = torch.float32)

tensor3 = torch.tensor([[11, 22],
                        [33, 44],
                        [55, 66]],
                       dtype = torch.float32)

In [ ]:
# Transpose

print(tensor2.T)

tensor([[1., 3., 5.],
        [2., 4., 6.]])


In [ ]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor2 = {tensor2.shape}, tensor3 = {tensor3.shape}\n")
print(f"New shapes: tensor2 = {tensor2.shape} (same as above), tensor3.T = {tensor3.T.shape}\n")
print(f"Multiplying: {tensor2.shape} * {tensor3.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor2, tensor3.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor2 = torch.Size([3, 2]), tensor3 = torch.Size([3, 2])

New shapes: tensor2 = torch.Size([3, 2]) (same as above), tensor3.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 55., 121., 187.],
        [121., 275., 429.],
        [187., 429., 671.]])

Output shape: torch.Size([3, 3])


In [ ]:
torch.mm(tensor2, tensor3.T)

tensor([[ 55., 121., 187.],
        [121., 275., 429.],
        [187., 429., 671.]])

In [ ]:
torch.manual_seed(42) # It's used in pytorch to generate same random number everytime.

linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input
                         out_features=6) # out_features = describes outer value
x = tensor2
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


# Min Max Mean Sum

In [ ]:
x = torch.arange(0, 200, 20)
x

tensor([  0,  20,  40,  60,  80, 100, 120, 140, 160, 180])

In [ ]:
print(f"Minimum(x): {x.min()}")
print(f"Maximum(x): {x.max()}")
print(f"Mean(x): {x.type(torch.float32).mean()}")
print(f"Sum(x): {x.sum()}")

Minimum(x): 0
Maximum(x): 180
Mean(x): 90.0
Sum(x): 900


In [ ]:
torch.max(x)
torch.min(x)
torch.mean(x.type(torch.float32))
torch.sum(x)

tensor(900)

In [ ]:
print(f"Max Value Index: {x.argmax()}")
print(f"Min Value Index: {x.argmin()}")

Max Value Index: 9
Min Value Index: 0


# Changing Tensor Datatype

In [ ]:
y = torch.arange(10., 100., 10.)
y.dtype

torch.float32

In [ ]:
y_float16 = y.type(torch.float16)
y_float16.dtype

torch.float16