<a href="https://colab.research.google.com/github/zaidensarii/Pytorch-Fundamentals/blob/main/Pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import torch

In [ ]:
print(torch.__version__)

2.2.1+cu121


Introduction to Tensors

Creating tensors

Pytorch tensors are created using 'torch.tensor()'

In [ ]:
# scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# Tensors

Tensor = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 6]]])

Tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 6]]])

In [ ]:
Tensor.ndim

3

In [ ]:
Tensor.shape

torch.Size([1, 3, 3])

Random Tensors

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

In [ ]:
# create a Random tensor of size (3, 4)

random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.1366, 0.9929, 0.6851, 0.2804],
        [0.0299, 0.6840, 0.0244, 0.5607],
        [0.0369, 0.7342, 0.6397, 0.0847]])

In [ ]:
random_tensor.ndim

2

In [ ]:
# creating a random tensor with similar shape to an image tensor

random_image_tensor = torch.rand(size=(224, 224, 3))
random_image_tensor.ndim, random_image_tensor.shape

(3, torch.Size([224, 224, 3]))