<a href="https://colab.research.google.com/github/zaidensarii/Pytorch-Fundamentals/blob/main/Pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Main Take away for deep Learning

**Start with random data --> Look at data --> Update random numbers --> Look at data --> Update random numbers**

Machine Learning models like neural networks manipulate and seek patterns in tensors.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import torch

In [2]:
print(torch.__version__)

2.2.1+cu121


Introduction to Tensors

Creating tensors

Pytorch tensors are created using 'torch.tensor()'

In [3]:
# scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# Tensors

Tensor = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 6]]])

Tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 6]]])

In [10]:
Tensor.ndim

3

In [11]:
Tensor.shape

torch.Size([1, 3, 3])

Random Tensors

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

In [12]:
# create a Random tensor of size (3, 4)

random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.4648, 0.1068, 0.3535, 0.5724],
        [0.8421, 0.6569, 0.9334, 0.4308],
        [0.3147, 0.4257, 0.1205, 0.3993]])

In [13]:
random_tensor.ndim

2

In [14]:
# creating a random tensor with similar shape to an image tensor

random_image_tensor = torch.rand(size=(224, 224, 3)) # height width Color channel
random_image_tensor.ndim, random_image_tensor.shape

(3, torch.Size([224, 224, 3]))

# Zeros and Ones

Creating tensors from zeros and ones

This happens a lot with masking (like masking some of the values in one tensor with zeros to let a model know not to learn on them)

In [15]:
zero = torch.zeros(size=(3, 224, 224))
zero

tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]])

In [16]:
one = torch.ones(size=(3, 34, 34))
one

tensor([[[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.]],

        [[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.]],

        [[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.]]])

# Creating a range of tensors and tensors-like


In [17]:
one_to_ten = torch.arange(start=0, end=10, step=2)
one_to_ten

tensor([0, 2, 4, 6, 8])

In [18]:
# creating tensors like

ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0])

# Tensor Datatypes


Tensors datatype is one of the three big errors you'll run into pytorch & deep learning.

1. tensors not right datatype
2. tensors not right shape
3. tensors not on the right device



In [19]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16,
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [20]:
float_64_tensor = float_32_tensor.type(torch.double)
float_64_tensor

tensor([3., 6., 9.], dtype=torch.float64)

# Getting information from tensors

In [23]:
some_tensor = torch.rand(size=(3,4))

print(some_tensor)
print(f"Shape of the tensor: {some_tensor.shape}")
print(f"Datatype of the tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}")

tensor([[0.7479, 0.9501, 0.7314, 0.9894],
        [0.2816, 0.7876, 0.2303, 0.9504],
        [0.9040, 0.1931, 0.7211, 0.3606]])
Shape of the tensor: torch.Size([3, 4])
Datatype of the tensor: torch.float32
Device tensor is stored on: cpu




```
# This is formatted as code
```

# Manipulating Tensors